### ISSUE TITLE
TypeScript equivalent help

### ISSUE THREAD

**Issue by kylemh** [bahmutov/next-and-cypress-example#104]
I've got everything in this example handled, plus I have:

`.nycrc`:
```json
{
  "extension": [
    ".js",
    ".jsx",
    ".ts",
    ".tsx"
  ],
  "extends": "@istanbuljs/nyc-config-typescript",
  "include": [
    "pages/**/*",
    "components/**/*",
    "hooks/**/*",
    "utils/**/*"
  ],
  "exclude": [
    "pages/api/__coverage__.js"
  ],
  "all": true,
  "sourceMap": true,
  "instrument": true
}
```

Plus in my `package.json`:
```json
"nyc": {
  "extends": "./.nycrc",
  "report-dir": "cypress-coverage",
  "reporter": [
    "json",
    "lcov"
  ]
},
```

Plus the edit needed to instrument TS inside `cypress/plugins/index.js`:
```ts
/**
 * @type {Cypress.PluginConfig}
 */
module.exports = (on: Cypress.PluginEvents, config: Cypress.PluginConfigOptions) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config

  const browserify = require('@cypress/browserify-preprocessor');
  const options = browserify.defaultOptions;
  options.browserifyOptions.transform[1][1].babelrc = true;
  options.typescript = require.resolve('typescript');

  require('@cypress/code-coverage/task')(on, config);
  on('file:preprocessor', browserify(options));

  return config;
};

```

The test runner runs, but I'm not seeing any coverage reported unless I do `cypress open`. Does it require `--record` flag if I use `cypress run`?

More importantly, the coverage report is reporting zeros across the board, but we have plenty of tests and should see _some_ coverage. I see the following error: 
```
⚠️ file /Users/kyle/Code/@air/next/.nyc_output/out.json has no coverage information
Did you forget to instrument your web application?
Read https://github.com/cypress-io/code-coverage#instrument-your-application```

**Comment by kylemh** [comment]
@bahmutov ready to open a PR to this and the README for @cypress/code-coverage once I get this all working!

**Comment by bahmutov** [comment]
Definitely

**Comment by kylemh** [comment]
Let me know if you see what's wrong, because it's eluding me.

**Comment by bahmutov** [comment]
@kylemh can you set up actual repo with Next.js and TypeScript so that once we figure it out, we can link to it from https://github.com/cypress-io/code-coverage#external-examples?

**Comment by kylemh** [comment]
I'm not quite sure how I resolved it, but I got it working!

https://github.com/kylemh/next-ts-with-cypress-coverage

Example contains:

- Next.js (from `create-next-app`)
- Cypress (obviously)
- TypeScript
- Instrumented coverage reporting
- @testing-library/react
- Instructions for typing custom commands
